apiVersion: apps/v1
kind: Deployment
metadata:
  name: front-end-deployment
  labels:
    app: front-deployment
spec:
  replicas: 5
  selector:
    matchLabels:
      app: frontend-pods
  template:
    metadata:
      labels:
        app: frontend-pods
    spec:
      containers:
        - name: front-end-container
          image: hacker123shiva/springbt-in-docker:latest
          ports:
            - containerPort: 8080
